name: CI

on: pull_request

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package -DskipTests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx

      - name: Build Success
        uses : rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}