name: CI
on:
  push:
    branches:
      - "dev"

env:
  IMAGE_NAME: ${{vars.APP_SERVICE_REPO}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package -DskipTests

      - name: Get Release Version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:${{ env.VERSION }}
            ${{env.IMAGE_NAME}}:latest
      
      - name: Build Success
        uses : rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Build Succeeded!
            Push to hub with following tag: 
              + ${{env.IMAGE_NAME}}:${{ env.VERSION }} 
              + ${{env.IMAGE_NAME}}:latest
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}